//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przychodnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepty
    {
        public int Id { get; set; }
        public int Pacjent_ID { get; set; }
        public string NazwaRecepty { get; set; }
        public int NumerRecepty { get; set; }
    
        public virtual Pacjenci Pacjenci { get; set; }
    }
}
